#! /usr/bin/env python3

import sys, random

if len(sys.argv) > 1:
    p = float(sys.argv[1])
else:
    p = 0.5

while 1:
    line = sys.stdin.readline()
    if not line:
        break
    line = line.strip()
    if not line or line[0] == '#':
        continue
    sp = line.split()
    if len(sp) != 2:
        print("syntax error", file=sys.stderr)
        sys.exit(1)

    if random.random() > p:
        print(sp[0], sp[1], 0)
    else:
        print(sp[0], sp[1], 1)
