#! /usr/bin/env python

import sys, random, string

if len(sys.argv) > 1:
    p = float(sys.argv[1])
else:
    p = 0.5

while 1:
    line = sys.stdin.readline()
    if not line:
        break
    line = string.strip(line)
    if not line or line[0] == '#':
        continue
    sp = string.split(line)
    if len(sp) != 2:
        print "syntax error"
        sys.exit(1)

    print sp[0], sp[1],

    if random.random() > p:
        print 0
    else:
        print 1
